export enum AssetsCategoryUesrAccessTypes {
  NAV_ASSETS_CATEGORY = "NAV_ASSETS_CATEGORY",
  ACTION_ASSETS_CATEGORY_LIST = "ACTION_ASSETS_CATEGORY_LIST",
  ASSETS_CATEGORY_LIST_ASSETS_CATEGORY_NAME = "ASSETS_CATEGORY_LIST_ASSETS_CATEGORY_NAME",
  ACTION_ASSETS_CATEGORY_ADD = "ACTION_ASSETS_CATEGORY_ADD",
  ACTION_ASSETS_CATEGORY_ONE_EDIT = "ACTION_ASSETS_CATEGORY_ONE_EDIT",
  ACTION_ASSETS_CATEGORY_ONE_DELETE = "ACTION_ASSETS_CATEGORY_ONE_DELETE"
}
export enum AssetsAllocationUesrAccessTypes {
  NAV_ASSETS_ALLOCATION = "NAV_ASSETS_ALLOCATION",
  ACTION_ASSETS_ALLOCATION_LIST_ASSETS_ALLOCATION_NAME = "ACTION_ASSETS_ALLOCATION_LIST_ASSETS_ALLOCATION_NAME",
  ACTION_ASSETS_ALLOCATION_ADD = "ACTION_ASSETS_ALLOCATION_ADD",
  ACTION_ASSETS_ALLOCATION_ONE_EDIT = "ACTION_ASSETS_ALLOCATION_ONE_EDIT",
  ACTION_ASSETS_ALLOCATION_ONE_DELETE = "ACTION_ASSETS_ALLOCATION_ONE_DELETE"
}
export enum AssetsLocationUserAccessTypes {
  NAV_ASSETS_LOCATION = "NAV_ASSETS_LOCATION",
  ACTION_ASSETS_LOCATION_LIST = "ACTION_ASSETS_LOCATION_LIST",
  ASSETS_LOCATION_LIST_ASSETS_LOCATION_NAME = "ASSETS_LOCATION_LIST_ASSETS_LOCATION_NAME",
  ACTION_ASSETS_LOCATION_ADD = "ACTION_ASSETS_LOCATION_ADD",
  ACTION_ASSETS_LOCATION_ONE_EDIT = "ACTION_ASSETS_LOCATION_ONE_EDIT",
  ACTION_ASSETS_LOCATION_ONE_DELETE = "ACTION_ASSETS_LOCATION_ONE_DELETE"
}
export enum AssetsReLocationUserAccessTypes {
  NAV_ASSETS_RELOCATION = "NAV_ASSETS_RELOCATION",
  ACTION_ASSETS_RELOCATION_LIST = "ACTION_ASSETS_RELOCATION_LIST",
  ASSETS_LOCATION_LIST_ASSETS_RELOCATION_NAME = "ASSETS_RELOCATION_LIST_ASSETS_RELOCATION_NAME",
  ACTION_ASSETS_RELOCATION_ADD = "ACTION_ASSETS_RELOCATION_ADD",
  ACTION_ASSETS_RELOCATION_ONE_EDIT = "ACTION_ASSETS_RELOCATION_ONE_EDIT",
  ACTION_ASSETS_RELOCATION_ONE_DELETE = "ACTION_ASSETS_RELOCATION_ONE_DELETE"
}
export enum AssetsRequestUserAccessTypes {
  NAV_ASSETS_REQUEST = "NAV_ASSETS_REQUEST",
  ACTION_ASSETS_REQUEST_LIST = "ACTION_ASSETS_REQUEST_LIST",
  ASSETS_LOCATION_LIST_ASSETS_REQUEST_NAME = "ASSETS_REQUEST_LIST_ASSETS_REQUEST_NAME",
  ACTION_ASSETS_REQUEST_ADD = "ACTION_ASSETS_REQUEST_ADD",
  ACTION_ASSETS_REQUEST_ONE_EDIT = "ACTION_ASSETS_REQUEST_ONE_EDIT",
  ACTION_ASSETS_REQUEST_ONE_DELETE = "ACTION_ASSETS_REQUEST_ONE_DELETE"
}
export enum WebsitesUserAccessTypes {
  NAV_WEBSITES = "NAV_WEBSITES",
  ACTION_WEBSITES_LIST = "ACTION_WEBSITES_LIST",
  WEBSITES_LIST_WEBSITES_NAME = "WEBSITES_LIST_WEBSITES_NAME",
  WEBSITES_LIST_GA_TAG = "WEBSITES_LIST_GA_TAG",
  ACTION_WEBSITES_ADD = "ACTION_WEBSITES_ADD",
  ACTION_WEBSITES_ONE_EDIT = "ACTION_WEBSITES_ONE_EDIT",
  ACTION_WEBSITES_ONE_DELETE = "ACTION_WEBSITES_ONE_DELETE"
}
export enum WebsitesBlogUserAccessTypes {
  NAV_WEBSITES_BLOG = "NAV_WEBSITES_BLOG",
  ACTION_WEBSITES_BLOG_LIST = "ACTION_WEBSITES_BLOG_LIST",
  WEBSITES_BLOG_LIST_WEBSITES_BLOG_NAME = "WEBSITES_BLOG_LIST_WEBSITES_BLOG_NAME",
  WEBSITES_BLOG_LIST_BLOG_TITLE = "WEBSITES_BLOG_LIST_BLOG_TITLE",
  WEBSITES_BLOG_LIST_BLOG_SUBTITLE = "WEBSITES_BLOG_LIST_BLOG_SUBTITLE",
  ACTION_WEBSITES_BLOG_ADD = "ACTION_WEBSITES_BLOG_ADD",
  ACTION_WEBSITES_BLOG_ONE_EDIT = "ACTION_WEBSITES_BLOG_ONE_EDIT",
  ACTION_WEBSITES_BLOG_ONE_DELETE = "ACTION_WEBSITES_BLOG_ONE_DELETE"
}
export enum WebsitesPageUserAccessTypes {
  NAV_WEBSITES_PAGES = "NAV_WEBSITES_PAGES",
  ACTION_WEBSITES_PAGES_LIST = "ACTION_WEBSITES_PAGES_LIST",
  WEBSITES_PAGES_LIST_WEBSITES_PAGES_NAME = "WEBSITES_PAGES_LIST_WEBSITES_PAGES_NAME",
  WEBSITES_PAGES_LIST_PAGE_URL = "WEBSITES_PAGES_LIST_PAGE_URL",
  ACTION_WEBSITES_PAGES_ADD = "ACTION_WEBSITES_PAGES_ADD",
  ACTION_WEBSITES_PAGES_ONE_EDIT = "ACTION_WEBSITES_PAGES_ONE_EDIT",
  ACTION_WEBSITES_PAGES_ONE_DELETE = "ACTION_WEBSITES_BLOG_ONE_DELETE"
}
export enum WebsitesTagesUserAccessTypes {
  NAV_WEBSITES_TAGS = "NAV_WEBSITES_TAGS",
  ACTION_WEBSITES_TAGS_LIST = "ACTION_WEBSITES_TAGS_LIST",
  WEBSITES_TAGS_LIST_WEBSITES_META_KEYWORD = "WEBSITES_TAGS_LIST_WEBSITES_META_KEYWORD",
  WEBSITES_TAGS_LIST_META_OG_TYPE = "WEBSITES_TAGS_LIST_META_OG_TYPE",
  WEBSITES_TAGS_LIST_META_TWITTER_TITLE = "WEBSITES_TAGS_LIST_META_TWITTER_TITLE",
  WEBSITES_TAGS_LIST_META_TWITTER_CARD = "WEBSITES_TAGS_LIST_META_TWITTER_CARD",
  ACTION_WEBSITES_TAGS_ADD = "ACTION_WEBSITES_TAGS_ADD",
  ACTION_WEBSITES_TAGS_ONE_EDIT = "ACTION_WEBSITES_TAGS_ONE_EDIT",
  ACTION_WEBSITES_TAGS_ONE_DELETE = "ACTION_WEBSITES_BLOG_ONE_DELETE"
}