export enum barcodeUserAccessType {
  NAV_BARCODE = "NAV_BARCODE"
}

export enum cartonBoxUserAccessType {
  NAV_CARTON_BOX = "NAV_CARTON_BOX",
  ACTION_CARTON_BOX_LIST = "NAV_CARTON_BOX_LIST",
  CARTON_BOX_LIST_BOX_NAME = "CARTON_BOX_LIST_BOX_NAME",
  CARTON_BOX_LIST_INNER_ITEMS_COUNT = "CARTON_BOX_LIST_INNER_ITEMS_COUNT",
  CARTON_BOX_LIST_DIMENSIONS = "CARTON_BOX_LIST_DIMENSIONS",
  CARTON_BOX_LIST_BOX_WEIGHT = "CARTON_BOX_LIST_BOX_WEIGHT",
  CARTON_BOX_LIST_PRODUCT_GROUP = "CARTON_BOX_LIST_PRODUCT_GROUP",
  ACTION_CARTON_BOX_ADD = "ACTION_CARTON_BOX_ADD",
  ACTION_CARTON_BOX_EDIT = "ACTION_CARTON_BOX_EDIT",
  ACTION_CARTON_BOX_DELETE = "ACTION_CARTON_BOX_DELETE",
}

export enum companyUserAccessType {
  NAV_COMPANY = "NAV_COMPANY",
  ACTION_COMPANY_LIST = "ACTION_COMPANY_LIST",
  ACTION_COMPANY_ADD = "ACTION_COMPANY_ADD",
  ACTION_COMPANY_EDIT = "ACTION_COMPANY_EDIT",
  ACTION_COMPANY_DELETE = "ACTION_COMPANY_DELETE",
  COMPANY_LIST_COMAPNY_NAME = "COMPANY_LIST_COMAPNY_NAME",
  COMPANY_LIST_WEBSITE_URL = "COMPANY_LIST_WEBSITE_URL",
  COMPANY_LIST_ADDRESS = "COMPANY_LIST_ADDRESS",
  COMPANY_LIST_GST_NO = "COMPANY_LIST_GST_NO",
  COMPANY_LIST_PHONE_NO = "COMPANY_LIST_PHONE_NO",
}

export enum companyBranchUserAccessType {
  NAV_COMPANY_BRANCH = "NAV_COMPANY_BRANCH",
  ACTION_COMPANY_BRANCH_LIST = "ACTION_COMPANY_BRANCH_LIST",
  ACTION_COMPANY_BRANCH_ADD = "ACTION_COMPANY_BRANCH_ADD",
  ACTION_COMPANY_BRANCH_EDIT = "ACTION_COMPANY_BRANCH_EDIT",
  ACTION_COMPANY_BRANCH_DELETE = "ACTION_COMPANY_BRANCH_DELETE",
  COMPANY_BRANCH_LIST_COMAPNY_NAME = "COMPANY_BRANCH_LIST_COMAPNY_NAME",
  COMPANY_BRANCH_LIST_BRANCH_NAME = "COMPANY_BRANCH_LIST_BRANCH_NAME",
}

export enum languageUserAccessType {
  NAV_LANGUAGE = "NAV_LANGUAGE",
  ACTION_LANGUAGE_LIST = "ACTION_LANGUAGE_LIST",
  ACTION_LANGUAGE_ADD = "ACTION_LANGUAGE_ADD",
  ACTION_LANGUAGE_EDIT = "ACTION_LANGUAGE_EDIT",
  ACTION_LANGUAGE_DELETE = "ACTION_LANGUAGE_DELETE",
  LANGUAGE_LIST_LANGUAGE = "LANGUAGE_LIST_LANGUAGE",
}

export enum locationUserAccessType {
  NAV_LOCATION = "NAV_LOCATION",
  ACTION_COUNTRY_LIST = "ACTION_COUNTRY_LIST",
  ACTION_COUNTRY_ADD = "ACTION_COUNTRY_ADD",
  ACTION_STATE_LIST = "ACTION_STATE_LIST",
  ACTION_STATE_ADD = "ACTION_STATE_ADD",
  ACTION_DISTRICTS_LIST = "ACTION_DISTRICTS_LIST",
  ACTION_DISTRICTS_ADD = "ACTION_DISTRICTS_ADD",
  ACTION_TEHSILS_LIST = "ACTION_TEHSILS_LIST",
  ACTION_TEHSILS_ADD = "ACTION_TEHSILS_ADD",
  ACTION_PINCODES_LIST = "ACTION_PINCODES_LIST",
  ACTION_PINCODES_ADD = "ACTION_PINCODES_ADD",
  ACTION_AREA_LIST = "ACTION_AREA_LIST",
  ACTION_AREA_ADD = "ACTION_AREA_ADD",
}

export enum productUserAccessType {
  NAV_PRODUCTS = "NAV_PRODUCTS",
  ACTION_PRODUCTS_LIST = "ACTION_PRODUCTS_LIST",
  ACTION_PRODUCTS_ADD = "ACTION_PRODUCTS_ADD",
  ACTION_PRODUCTS_EDIT = "ACTION_PRODUCTS_EDIT",
  ACTION_PRODUCTS_DELETE = "ACTION_PRODUCTS_DELETE",
  LANGUAGE_LIST_LANGUAGE = "LANGUAGE_LIST_LANGUAGE",
  PRODUCTS_LIST_PRODUCT_CODE = "PRODUCTS_LIST_PRODUCT_CODE",
  PRODUCTS_LIST_PRODUCT_NAME = "PRODUCTS_LIST_PRODUCT_NAME",
  PRODUCTS_LIST_CATEGORY = "PRODUCTS_LIST_CATEGORY",
  PRODUCTS_LIST_SUB_CATEGORY = "PRODUCTS_LIST_SUB_CATEGORY",
  PRODUCTS_LIST_PRODUCT_GROUP = "PRODUCTS_LIST_PRODUCT_GROUP",
}

export enum artistUserAccessType {
  NAV_ARTIST = "NAV_ARTIST",
  ACTION_ARTIST_LIST = "ACTION_ARTIST_LIST",
  ACTION_ARTIST_ADD = "ACTION_ARTIST_ADD",
  ACTION_ARTIST_EDIT = "ACTION_ARTIST_EDIT",
  ACTION_ARTIST_DELETE = "ACTION_ARTIST_DELETE",
  ARTIST_LIST_ARTIST_NAME = "ARTIST_LIST_ARTIST_NAME",
}

export enum channelCategoryUserAccessType {
  NAV_CHANNEL_CATEGORY = "NAV_CHANNEL_CATEGORY",
  ACTION_CHANNEL_CATEGORY_LIST = "ACTION_CHANNEL_CATEGORY_LIST",
  ACTION_CHANNEL_CATEGORY_ADD = "ACTION_CHANNEL_CATEGORY_ADD",
  ACTION_CHANNEL_CATEGORY_EDIT = "ACTION_CHANNEL_CATEGORY_EDIT",
  ACTION_CHANNEL_CATEGORY_DELETE = "ACTION_CHANNEL_CATEGORY_DELETE",
  CATEGORY_LIST_CHANNEL_CATEGORY_NAME = "CATEGORY_LIST_CHANNEL_CATEGORY_NAME",
}

export enum channelGroupUserAccessType {
  NAV_CHANNEL_GROUP = "NAV_CHANNEL_GROUP",
  ACTION_CHANNEL_GROUP_LIST = "ACTION_CHANNEL_GROUP_LIST",
  ACTION_CHANNEL_GROUP_ADD = "ACTION_CHANNEL_GROUP_ADD",
  ACTION_CHANNEL_GROUP_EDIT = "ACTION_CHANNEL_GROUP_EDIT",
  ACTION_CHANNEL_GROUP_DELETE = "ACTION_CHANNEL_GROUP_DELETE",
  CHANNEL_GROUP_LIST_CHANNEL_GROUP_NAME = "CHANNEL_GROUP_LIST_CHANNEL_GROUP_NAME",
}

export enum channelManagementUserAccessType {
  NAV_CHANNEL_MANAGEMENT = "NAV_CHANNEL_MANAGEMENT",
  ACTION_CHANNEL_MANAGEMENT_LIST = "ACTION_CHANNEL_MANAGEMENT_LIST",
  ACTION_CHANNEL_MANAGEMENT_ADD = "ACTION_CHANNEL_MANAGEMENT_ADD",
  ACTION_CHANNEL_MANAGEMENT_EDIT = "ACTION_CHANNEL_MANAGEMENT_EDIT",
  ACTION_CHANNEL_MANAGEMENT_DELETE = "ACTION_CHANNEL_MANAGEMENT_DELETE",
  CHANNEL_MANAGEMENT_LIST_CHANNEL_NAME = "CHANNEL_MANAGEMENT_LIST_CHANNEL_NAME",
  CHANNEL_MANAGEMENT_LIST_CHANNEL_GROUP = "CHANNEL_MANAGEMENT_LIST_CHANNEL_GROUP",
  CHANNEL_MANAGEMENT_LIST_CONTACT_PERSON = "CHANNEL_MANAGEMENT_LIST_CONTACT_PERSON",
  CHANNEL_MANAGEMENT_LIST_MOBILE = "CHANNEL_MANAGEMENT_LIST_MOBILE",
  CHANNEL_MANAGEMENT_LIST_EMAIL = "CHANNEL_MANAGEMENT_LIST_EMAIL",
}

export enum competitorUserAccessType {
  NAV_COMPETITOR = "NAV_COMPETITOR",
  ACTION_COMPETITOR_LIST = "ACTION_COMPETITOR_LIST",
  ACTION_COMPETITOR_ADD = "ACTION_COMPETITOR_ADD",
  ACTION_COMPETITOR_EDIT = "ACTION_COMPETITOR_EDIT",
  ACTION_COMPETITOR_DELETE = "ACTION_COMPETITOR_DELETE",
  COMPETITOR_LIST_DATE = "COMPETITOR_LIST_DATE",
  COMPETITOR_LIST_START_TIME = "COMPETITOR_LIST_START_TIME",
  COMPETITOR_LIST_START_END = "COMPETITOR_LIST_START_END",
  COMPETITOR_LIST_PRODUCT_NAME = "COMPETITOR_LIST_PRODUCT_NAME",
  COMPETITOR_LIST_MOBILE_NO = "COMPETITOR_LIST_MOBILE_NO",
  COMPETITOR_LIST_PRICE_MRP = "COMPETITOR_LIST_PRICE_MRP",
  COMPETITOR_LIST_COMPETITOR_NAME = "COMPETITOR_LIST_COMPETITOR_NAME",
}

export enum customerPageUserAccessType {
  NAV_CUSTOMER_PAGE = "NAV_CUSTOMER_PAGE",
}

export enum inboundUserAccessType {
  NAV_INBOUND = "NAV_INBOUND",
}

export enum didManagementUserAccessType {
  NAV_DID_MANAGEMENT = "NAV_DID_MANAGEMENT",
  ACTION_DID_MANAGEMENT_LIST = "ACTION_DID_MANAGEMENT_LIST",
  ACTION_DID_MANAGEMENT_ADD = "ACTION_DID_MANAGEMENT_ADD",
  ACTION_DID_MANAGEMENT_EDIT = "ACTION_DID_MANAGEMENT_EDIT",
  ACTION_DID_MANAGEMENT_DELETE = "ACTION_DID_MANAGEMENT_DELETE",
  DID_MANAGEMENT_LIST_DID_NUMBER = "DID_MANAGEMENT_LIST_DID_NUMBER",
  DID_MANAGEMENT_LIST_DID_SCHEMA_NAME = "DID_MANAGEMENT_LIST_DID_SCHEMA_NAME",
  DID_MANAGEMENT_LIST_CHANNEL_NAME = "DID_MANAGEMENT_LIST_CHANNEL_NAME",
  DID_MANAGEMENT_LIST_SLOT_NAME = "DID_MANAGEMENT_LIST_SLOT_NAME",
}

export enum slotManagementUserAccessType {
  NAV_SLOT_MANAGEMENT = "NAV_SLOT_MANAGEMENT",
  ACTION_SLOT_MANAGEMENT_LIST = "ACTION_SLOT_MANAGEMENT_LIST",
  ACTION_SLOT_MANAGEMENT_ADD = "ACTION_SLOT_MANAGEMENT_ADD",
  ACTION_SLOT_MANAGEMENT_EDIT = "ACTION_SLOT_MANAGEMENT_EDIT",
  ACTION_SLOT_MANAGEMENT_DELETE = "ACTION_SLOT_MANAGEMENT_DELETE",
  SLOT_MANAGEMENT_LIST_SLOT_NAME = "SLOT_MANAGEMENT_LIST_SLOT_NAME",
  SLOT_MANAGEMENT_LIST_CHANNEL_GROUP = "SLOT_MANAGEMENT_LIST_CHANNEL_GROUP",
  SLOT_MANAGEMENT_LIST_CHANNEL_NAME = "SLOT_MANAGEMENT_LIST_CHANNEL_NAME",
  SLOT_MANAGEMENT_LIST_TAPE_NAME = "SLOT_MANAGEMENT_LIST_TAPE_NAME",
  SLOT_MANAGEMENT_LIST_START_TIME = "SLOT_MANAGEMENT_LIST_START_TIME",
  SLOT_MANAGEMENT_LIST_END_TIME = "SLOT_MANAGEMENT_LIST_END_TIME",
  SLOT_MANAGEMENT_LIST_PAUSE_PLAY = "SLOT_MANAGEMENT_LIST_PAUSE_PLAY",
}

export enum tapeManagementUserAccessType {
  NAV_TAPE_MANAGEMENT = "NAV_TAPE_MANAGEMENT",
  ACTION_TAPE_MANAGEMENT_LIST = "ACTION_TAPE_MANAGEMENT_LIST",
  ACTION_TAPE_MANAGEMENT_ADD = "ACTION_TAPE_MANAGEMENT_ADD",
  ACTION_TAPE_MANAGEMENT_EDIT = "ACTION_TAPE_MANAGEMENT_EDIT",
  ACTION_TAPE_MANAGEMENT_DELETE = "ACTION_TAPE_MANAGEMENT_DELETE",
  TAPE_MANAGEMENT_LIST_TAPE_NAME = "TAPE_MANAGEMENT_LIST_TAPE_NAME",
  TAPE_MANAGEMENT_LIST_TAPE_TYPE = "TAPE_MANAGEMENT_LIST_TAPE_TYPE",
  TAPE_MANAGEMENT_LIST_SCHEME = "TAPE_MANAGEMENT_LIST_SCHEME",
  TAPE_MANAGEMENT_LIST_LANGUAGE = "TAPE_MANAGEMENT_LIST_LANGUAGE",
}
