import React from 'react'

const EwbInvoice = () => {
    const tableHead = 'border-r   text-start'
    const tableCell = 'border-r '
    return (
        <>
            <div className="bg-slate-500 py-10">
                <div className="bg-white  p-6 w-[940px] mx-auto my-auto">
                    <div className=" border py-2">
                        <div className="border py-1 mx-2">
                            <p className="text-center font-extrabold text-[22px]">
                                E-Way Bill System
                            </p>
                            <div className="flex justify-center">
                                <img
                                    className="h-[120px] mt-4"
                                    src="https://media.istockphoto.com/id/828088276/vector/qr-code-illustration.jpg?s=612x612&w=0&k=20&c=FnA7agr57XpFi081ZT5sEmxhLytMBlK4vzdQxt8A70M="
                                    alt=""
                                />
                            </div>
                        </div>

                        <div className="border  mx-2 mt-2 ">
                            <div className="grid grid-cols-12 border-b ">
                                <p className=" col-span-5 border-r p-2 ">
                                    E-Way Bill No:{' '}
                                </p>
                                <p className="col-span-7 p-2 font-bold">
                                    6615 8680 4749
                                </p>
                            </div>
                            <div className="grid grid-cols-12 border-b  ">
                                <p className=" col-span-5 border-r p-2 ">
                                    E-Way Bill Date:{' '}
                                </p>
                                <p className="col-span-7 p-2 font-bold">
                                    11/07/2023 05:03 PM
                                </p>
                            </div>
                            <div className="grid grid-cols-12 border-b  ">
                                <p className=" col-span-5 border-r p-2 ">
                                    Generated By:{' '}
                                </p>
                                <p className="col-span-7 p-2 font-bold">
                                    23AATFT1962F1ZZ - Telemart
                                </p>
                            </div>
                            <div className="grid grid-cols-12 border-b  ">
                                <p className=" col-span-5 border-r p-2 ">
                                    Valid From:{' '}
                                </p>
                                <p className="col-span-7 p-2 font-bold">
                                    11/07/2023 05:03 PM [ 896 Kms]
                                </p>
                            </div>
                            <div className="grid grid-cols-12  ">
                                <p className=" col-span-5 border-r p-2 ">
                                    Valid Untill:{' '}
                                </p>
                                <p className="col-span-7 p-2 font-bold">
                                    16/07/2023 11:59 PM
                                </p>
                            </div>
                        </div>

                        {/* part-A */}
                        <div className="border border-t-0 mx-2 ">
                            <p className="col-span-7 p-2 font-bold  border-b">
                                Part - A
                            </p>
                            <div className="grid grid-cols-12 border-y ">
                                <p className=" col-span-5 border-r p-2 ">
                                    GSTIN of Supplier{' '}
                                </p>
                                <p className="col-span-7 p-2 font-bold">
                                    23AATFT1962F1ZZ, Telemart
                                </p>
                            </div>
                            <div className="grid grid-cols-12 border-b  ">
                                <p className=" col-span-5 border-r p-2 ">
                                    Place of Dispatch{' '}
                                </p>
                                <p className="col-span-7 p-2 font-bold">
                                    Indore, Madhya Pradesh - 452020
                                </p>
                            </div>
                            <div className="grid grid-cols-12 border-b  ">
                                <p className=" col-span-5 border-r p-2 ">
                                    {' '}
                                    GSTIN of Recipient
                                </p>
                                <p className="col-span-7 p-2 font-bold">
                                    09BAT PJ554 7D1ZC , SHREE MAHAKAL
                                    ENTERPRISES
                                </p>
                            </div>
                            <div className="grid grid-cols-12 border-b  ">
                                <p className=" col-span-5 border-r p-2 ">
                                    Place of Delivery{' '}
                                </p>
                                <p className="col-span-7 p-2 font-bold">
                                    Meerut, Uttar Pradesh - 250002
                                </p>
                            </div>
                            <div className="grid grid-cols-12 border-b  ">
                                <p className=" col-span-5 border-r p-2 ">
                                    Document No{' '}
                                </p>
                                <p className="col-span-7 p-2 font-bold">
                                    Tel-Y24-0002012
                                </p>
                            </div>
                            <div className="grid grid-cols-12 border-b  ">
                                <p className=" col-span-5 border-r p-2 ">
                                    Document Date{' '}
                                </p>
                                <p className="col-span-7 p-2 font-bold">
                                    11/07/2023
                                </p>
                            </div>
                            <div className="grid grid-cols-12 border-b  ">
                                <p className=" col-span-5 border-r p-2 ">
                                    Transaction Type{' '}
                                </p>
                                <p className="col-span-7 p-2 font-bold">
                                    Regular
                                </p>
                            </div>
                            <div className="grid grid-cols-12 border-b  ">
                                <p className=" col-span-5 border-r p-2 ">
                                    Value of Goods{' '}
                                </p>
                                <p className="col-span-7 p-2 font-bold">
                                    125440.00
                                </p>
                            </div>
                            <div className="grid grid-cols-12 border-b  ">
                                <p className=" col-span-5 border-r p-2 ">
                                    HSN Code{' '}
                                </p>
                                <p className="col-span-7 p-2 font-bold">
                                    30049011 - DRINK STOP -DEFAULT - (+3)
                                </p>
                            </div>
                            <div className="grid grid-cols-12 border-b  ">
                                <p className=" col-span-5 border-r p-2 ">
                                    Reason for Transportation{' '}
                                </p>
                                <p className="col-span-7 p-2 font-bold">
                                    Outward - SUPPLY
                                </p>
                            </div>
                            <div className="grid grid-cols-12  ">
                                <p className=" col-span-5 border-r p-2 ">
                                    Transporter{' '}
                                </p>
                                <p className="col-span-7 p-2 font-bold">
                                    07AABCC8298E1ZH & TRACKON COURIERS PRIVATE
                                    LIMITED
                                </p>
                            </div>
                        </div>
                        {/* part-B */}
                        <p className="col-span-7 p-2 font-bold  border border-t-0 mx-2">
                            Part - A
                        </p>
                        <div className="border border-t-0 mx-2 p-2">
                            <table width="100%" className="">
                                <thead className="border ">
                                    <tr>
                                        <th className={tableHead}>Mode</th>
                                        <th className={tableHead}>
                                            Vehicle / Trans <br /> Doc No & Dt.
                                        </th>
                                        <th className={tableHead}>From</th>
                                        <th className={tableHead}>
                                            Entered Date
                                        </th>
                                        <th className={tableHead}>
                                            Entered By{' '}
                                        </th>
                                        <th className={tableHead}>
                                            CEWB No. (if any){' '}
                                        </th>
                                        <th className={tableHead}>
                                            Multi Veh.Info (if any)
                                        </th>
                                    </tr>
                                </thead>
                                <tbody className="border-l border-b">
                                    <tr>
                                        <td className={tableCell}>ROAD</td>
                                        <td className={tableCell}>
                                            MP09R7158 & 500311714598 &11/07/2023
                                        </td>
                                        <td className={tableCell}>Indore</td>
                                        <td className={tableCell}>
                                            11/07/2023 05:03PM
                                        </td>
                                        <td className={tableCell}>
                                            23AATFT1962F1ZZ
                                        </td>
                                        <td className={tableCell}>0</td>
                                        <td className={tableCell}>-</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        {/* code */}
                        <div className="border m-2 flex justify-center">
                            <img
                                className="h-[80px]"
                                src="https://pageloot.com/wp-content/uploads/2021/10/Example-of-a-barcode-scanner-1024x414.jpg"
                                alt=""
                            />
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default EwbInvoice
