export type CallerResponse = {
    _id: string
    rowIndex: number | string
    didNo: string
    ageGroup: string
    agentId: string
    agentName: string
    comanyId: string
    alternateNo: string
    mobileNo: string
    autoFillingShippingAddress: string
    callType: string
    campaign: string
    customerName: string
    deliveryTimeAndDate: string
    countryId: string
    stateId: string
    districtId: string
    tehsilId: string
    schemeId: string
    pincodeId: string
    countryLabel: string
    stateLabel: string
    districtLabel: string
    tehsilLabel: string
    pincodeLabel: string
    areaLabel: string
    schemeName: string
    pincodeSecondId: null
    areaId: string
    emailId: string
    flagStatus: string
    gender: string
    houseNumber: string
    incomingCallerNo: string
    landmark: string
    medicalIssue: string[]
    orderFor: string
    paymentMode: string
    productGroupId: string
    remark: string
    shcemeQuantity: number
    socialMedia: {
        facebook: string
        instagram: string
        _id: string
    }
    streetNumber: string
    typeOfAddress: string
    whatsappNo: string
    price: number
    deliveryCharges: number
    totalAmount: number
    dispositionLevelTwoId: string
    dispositionLevelThreeId: string
    isDeleted: false
    isActive: true
    createdAt: string
    updatedAt: string
    __v: number
    dispositionLevelTwoLabel: string
    dispositionLevelThreeLabel: string
    agentDistrictLabel: string
}

export type CallerFormBody = {
    didNo: string
    ageGroup: string
    mobileNo: string
    alternateNo: string
    autoFillingShippingAddress: string
    callType: string
    campaign: string
    customerName: string
    deliveryTimeAndDate: string
    countryId: string
    stateId: string
    districtId: string
    tehsilId: string
    schemeId: string
    schemeName: string
    pincodeId: string
    pincodeSecondId: string
    villageId: null
    areaId: null
    emailId: string
    flagStatus: string
    gender: string
    houseNumber: string
    incomingCallerNo: string
    landmark: string
    medicalIssue: string[]
    orderFor: string
    paymentMode: string
    productGroupId: string
    isRecording?: boolean
    remark: string
    shcemeQuantity: number
    socialMedia: {
        facebook: string
        instagram: string
    }
    streetNumber: string
    typeOfAddress: string
    whatsappNo: string
    price: number
    deliveryCharges: number
    totalAmount: number
    dispositionLevelTwoId: string
    dispositionLevelThreeId: string
}

export type UpdateCallerForm = {
    body: {
        didNo: string
        ageGroup: string
        mobileNo: string
        alternateNo: string
        autoFillingShippingAddress: string
        callType: string
        campaign: string
        customerName: string
        deliveryTimeAndDate: string
        countryId: string
        stateId: string
        districtId: string
        tehsilId: string
        schemeId: string
        schemeName: string
        pincodeId: string
        pincodeSecondId: string
        // villageId: null
        areaId: null
        emailId: string
        flagStatus: string
        gender: string
        houseNumber: string
        incomingCallerNo: string
        landmark: string
        medicalIssue: string[]
        orderFor: string
        paymentMode: string
        productGroupId: string
        isRecording?: boolean
        remark: string
        shcemeQuantity: number
        socialMedia: {
            facebook: string
            instagram: string
        }
        streetNumber: string
        typeOfAddress: string
        whatsappNo: string
        price: number
        deliveryCharges: number
        totalAmount: number
        dispositionLevelTwoId: string
        dispositionLevelThreeId: string
    }
    id: string
}
