export type WarehousesListResponse = {
  name: string;
  address: string;
  pincode: string;
  state: string;
  district: string;
  contactNo: string;
  mobile: string;
  gst_no: string;
  type: string;
  vendor: string;
  invoicePrefix: string;
  invoiceNo: string;
  barcodePrefix: string;
  cancellationHours: string;
  againstCForm: boolean;
  isBranchOffice: boolean;
  comapny: string;
  blueDartAreaCode: string;
  blueDartRouteCode: string;
  blueDartCustomerName: string;
  delhiverySurfacePickupLocation: string;
  delhiveryAirPickupLocation: string;
  is_active: boolean;
  is_deleted: boolean;
  createdAt: string;
  updatedAt: string;
  _id: string;
  __v: number;
};

export type AddWarehouse = {
  name: string;
  address: string;
  pincode: string;
  state: string;
  district: string;
  contactNo: string;
  mobile: string;
  gst_no: string;
  type: string;
  vendor: string;
  invoicePrefix: string;
  invoiceNo: string;
  barcodePrefix: string;
  cancellationHours: string;
  againstCForm: boolean;
  isBranchOffice: boolean;
  comapny: string;
  blueDartAreaCode: string;
  blueDartRouteCode: string;
  blueDartCustomerName: string;
  delhiverySurfacePickupLocation: string;
  delhiveryAirPickupLocation: string;
};

export type UpdateWarehouse = {
  body: {
    name: string;
    address: string;
    pincode: string;
    state: string;
    district: string;
    contactNo: string;
    mobile: string;
    gst_no: string;
    type: string;
    vendor: string;
    invoicePrefix: string;
    invoiceNo: string;
    barcodePrefix: string;
    cancellationHours: string;
    againstCForm: boolean;
    isBranchOffice: boolean;
    comapny: string;
    blueDartAreaCode: string;
    blueDartRouteCode: string;
    blueDartCustomerName: string;
    delhiverySurfacePickupLocation: string;
    delhiveryAirPickupLocation: string;
  };
  id: string;
};
